WITH amountT as(
        SELECT PRODUCT_ID , SUM(AMOUNT) AS AMOUNT
        FROM FOOD_ORDER
        WHERE YEAR(PRODUCE_DATE) = 2022 
            AND MONTH(PRODUCE_DATE) = 5
        GROUP BY PRODUCT_ID
)
# 5월 생산일자인 것들중 상품 번호 별 총 생산량
SELECT 
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    # P.PRICE,
    # T.AMOUNT,
    (P.PRICE * T.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT P JOIN amountT T
ON P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY 3 DESC ,1 ASC
# 총매출 = FOOD_PRODUCT.PRICE * FOOD_ORDER.AMOUNT