-- 코드를 입력하세요
# 7월 아이스크림 총 주문량과 상반기의 아이스크림 총 주문량의 합
# 같은 맛의 아이스크림이라도 다른 출하 번호 있으니 생각
WITH JULYORDER AS(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)
SELECT H.FLAVOR
FROM FIRST_HALF H JOIN JULYORDER J
ON H.FLAVOR = J.FLAVOR
ORDER BY H.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3