# 부서별 평균 연봉, 소수점 첫째'반올'
SELECT
    D.DEPT_ID,
    D.DEPT_NAME_EN,
    K.AVG_SAL
FROM HR_DEPARTMENT D JOIN
(SELECT DEPT_ID, ROUND(AVG(SAL),0) AS AVG_SAL
FROM HR_EMPLOYEES 
GROUP BY DEPT_ID) K
ON D.DEPT_ID = K.DEPT_ID
ORDER BY 3 DESC;