# 카테고리별로 최대 가격인 상품 표시인데, 카테고리 제한이 있음


SELECT 
    D1.CATEGORY,
    D2.PRICE AS MAX_PRICE,
    D1.PRODUCT_NAME
FROM FOOD_PRODUCT D1 
JOIN
    (SELECT CATEGORY,MAX(PRICE) AS PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ) D2
ON D1.CATEGORY = D2.CATEGORY 
AND D1.PRICE = D2.PRICE
ORDER BY 2 DESC;