
select 
    b.BOOK_ID as BOOK_ID,
    A.AUTHOR_NAME,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') as PUBLISHED_DATE

FROM AUTHOR A JOIN 
(SELECT *
FROM BOOK 
WHERE CATEGORY = '경제') B
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC;